# compose.yaml

version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://api_user:Fefis280559@database:5432/api_cloud
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - database
    volumes:
      - ./app:/app

  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=Fefis280559
      - POSTGRES_DB=api_cloud
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
